### ISSUE TITLE
npm run build 报错失败

### ISSUE THREAD

**Issue by rubbish822** [wdlhao/vue2-element-touzi-admin#25]
deb_permission 分支，
0 info it worked if it ends with ok
1 verbose cli [ '/home/ivan/.nvm/versions/node/v10.16.3/bin/node',
1 verbose cli   '/home/ivan/.nvm/versions/node/v10.16.3/lib/node_modules/cnpm/node_modules/.bin/npm',
1 verbose cli   '--userconfig=/home/ivan/.cnpmrc',
1 verbose cli   '--disturl=https://npm.taobao.org/mirrors/node',
1 verbose cli   '--registry=https://r.npm.taobao.org',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.12.0
3 info using node@v10.16.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle vue@0.1.0~prebuild: vue@0.1.0
6 info lifecycle vue@0.1.0~build: vue@0.1.0
7 verbose lifecycle vue@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle vue@0.1.0~build: PATH: /home/ivan/.nvm/versions/node/v10.16.3/lib/node_modules/cnpm/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ivan/github/vue2-element-touzi-admin/node_modules/.bin:/home/ivan/.nvm/versions/node/v10.16.3/bin:/home/ivan/.pyenv/plugins/pyenv-virtualenv/shims:/home/ivan/.pyenv/plugins/pyenv-virtualenv/shims:/home/ivan/.pyenv/shims:/home/ivan/.pyenv/bin:/home/ivan/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin=:/usr/local/go/bin
9 verbose lifecycle vue@0.1.0~build: CWD: /home/ivan/github/vue2-element-touzi-admin
10 silly lifecycle vue@0.1.0~build: Args: [ '-c', 'vue-cli-service build' ]
11 silly lifecycle vue@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle vue@0.1.0~build: Failed to exec build script
13 verbose stack Error: vue@0.1.0 build: `vue-cli-service build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/ivan/.nvm/versions/node/v10.16.3/lib/node_modules/cnpm/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/ivan/.nvm/versions/node/v10.16.3/lib/node_modules/cnpm/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid vue@0.1.0
15 verbose cwd /home/ivan/github/vue2-element-touzi-admin
16 verbose Linux 4.15.0-54-generic
17 verbose argv "/home/ivan/.nvm/versions/node/v10.16.3/bin/node" "/home/ivan/.nvm/versions/node/v10.16.3/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/home/ivan/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=https://r.npm.taobao.org" "run" "build"
18 verbose node v10.16.3
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 1
22 error vue@0.1.0 build: `vue-cli-service build`
22 error Exit status 1
23 error Failed at the vue@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by wdlhao** [comment]
改了什么东西，原始版本没有这些报错。
